<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="FFMpegCore" Version="5.4.0" />
    <PackageVersion Include="TencentCloudSDK.Asr" Version="3.0.1442" />
    <PackageVersion Include="Tencent.QCloud.Cos.Sdk" Version="5.4.51" />
    <PackageVersion Include="System.Security.Cryptography.ProtectedData" Version="10.0.10" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="MSTest" Version="4.3.2" />
  </ItemGroup>
</Project>

