<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <AssemblyName>AccessibleVideoToText.Infrastructure</AssemblyName>
    <RootNamespace>AccessibleVideoToText.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AccessibleVideoToText.Core\AccessibleVideoToText.Core.csproj" />
    <PackageReference Include="FFMpegCore" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
    <PackageReference Include="TencentCloudSDK.Asr" />
    <PackageReference Include="Tencent.QCloud.Cos.Sdk" />
  </ItemGroup>
</Project>
